### ISSUE TITLE
When loading '⁨vocbuilderAI⁩':

### ISSUE THREAD

**Issue by JSY88** [soanseng/vocbuilderAI#3]
Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨vocbuilderAI⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "C:\Users\ss\AppData\Roaming\Anki2\addons21\1754806193\__init__.py", line 27, in <module>
    from openai import OpenAI
ImportError: cannot import name 'OpenAI' from 'openai' (C:\Users\ss\AppData\Roaming\Anki2\addons21\1416178071\vendor\openai\__init__.py)

**Comment by soanseng** [comment]
I drop the openai dependency, please use version 0.4
